# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('register_name', models.CharField(max_length=30)),
                ('register_datetime', models.DateTimeField()),
                ('update_name', models.CharField(max_length=30)),
                ('update_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_no', models.PositiveIntegerField(default=1)),
                ('register_name', models.CharField(max_length=30)),
                ('register_datetime', models.DateTimeField()),
                ('update_name', models.CharField(max_length=30)),
                ('update_datetime', models.DateTimeField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PythonBoard.Topic')),
            ],
        ),
    ]
